### PR TITLE
Standardize

### PR DESCRIPTION
**Pull request by tung-nd**
An effort to clean and standardize the code:
1. Instead of having a `rollout` function and an `upsample` function, we now have a unified `evaluation` function used for evaluating models.
2. Standardize the shape of the prediction to [B, C, H, W]. This is consistent with all metrics and losses.
3. Remove redundant code in forecasting and downscaling Module classes, and make changes to adhere to changes in model components and metrics.

### CODE REVIEW

**Comment by tung-nd** [comment]
@se0ngbin now we also compute w_mse during evaluation, which can be used for early stopping

**Review by jasonjewik — COMMENTED** [review]
LGTM, but we should update the tutorial notebooks (must do) and add docstrings (could be done later) before merging. For example, it wasn't clear to me what `log_postfix` was until I saw it being used in `forecast.py`.

**Comment by jasonjewik** [comment]
If you can't get around to doing these, I'll do it myself sometime in the next couple days.

**Comment by tung-nd** [comment]
Will really appreciate if you can do it :)

**Comment by jasonjewik** [comment]
Just checked the notebooks. Seems fine to me. Approved for merge.

**Pull request merged**
