### PR TITLE
Added early stopping functionality for trainers

### PR DESCRIPTION
**Pull request by se0ngbin**
Default patience is 5 and uses min of metric val/w_mse

### CODE REVIEW

**Comment by tung-nd** [comment]
this works well for forecasting but I'm unsure about downscaling where during validation we do not compute w_mse

**Review by jasonjewik — CHANGES_REQUESTED** [review]
Agree with @tung-nd. Is there a way you can parameterize the metric that is tracked for early stopping?

**Comment by se0ngbin** [comment]
I should be able to do that. For downscaling, what metric should I use?

**Comment by jasonjewik** [comment]
Actually, @tung-nd looking at the metrics code, I think we should be using MSE for downscaling validation. https://github.com/aditya-grover/climate-learn/blob/54aba4d44cf2214fdaa23a1bb61b2507b1e11cbb/src/climate_learn/models/modules/utils/metrics.py#L161

**Comment by tung-nd** [comment]
Yes we can use MSE for downscaling, and W_MSE for forecasting

**Comment by se0ngbin** [comment]
I changed the Trainer module so that
1. early stopping is turned off by default
2. when early stopping is turned on, patience is 5 by default
3. the task (downscaling or forecasting) must be specified so that the correct metric can be used

**Pull request merged**
